### ISSUE TITLE
Document http request duration

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#1050]
We should document that request duration times are now logged in microseconds.

In this log excerpt:

```
[07/Mar/2017:10:53:33 +0000] "POST /query?chunked=true&db=telegraf&epoch=ns&q=select+%2A+from+cpu+where+time+%3E+now%28%29+-+10m  HTTP/1.1" 200 3121 "-" "InfluxDBShell/1.2.1-rc4-c1.2.2~rc6" 4f217136-0324-11e7-952a-000000000000 54682
```

the last number is query duration in microseconds

We should probably fully document the log line for queries and writes as well

**Comment by e-dard** [comment]
Relevant code is here: https://github.com/influxdata/influxdb/blob/master/services/httpd/response_logger.go#L103-L117

**Comment by stevebang** [comment]
@e-dard In the comment above, it says that the last number in the log excerpt is "the query duration in microseconds". But the header on this issue is HTTP request duration. You pointed to the relevant code, which doesn't make it clear to me whether the value represents the HTTP request duration or the query duration. Can you clarify this for me? 

A customer is looking for "query duration" to discover which queries might be significant spikes in query durations. If the last number in that log line is query duration, I guess that they could filter and sort to find the exceptionally long (slow?) queries.

**Comment by stevebang** [comment]
See this for reference
http://httpd.apache.org/docs/current/mod/mod_log_config.html

**Comment by pierwill** [comment]
The HTTP  access log format is documented here: https://docs.influxdata.com/influxdb/v1.7/administration/logs/#http-access-log-format.
