### ISSUE TITLE
Multiple host addition

### ISSUE THREAD

**Issue by pratibhadeepti** [influxdata/docs.influxdata.com#1145]
###### What products and version are you using?
product is complete tick stack configured in one system. Now I wanna add more hosts so that I can monitor them so can anyone tell me how can i do so?

**Comment by timhallinflux** [comment]
@pratibhadeepti to make sure I understand your question... you have the TICK stack installed on a single node.  Now, you would like to use it to monitor some other machines?  

If so, that is all about deploying and configuring Telegraf to gather the stats you want from those other machines and feeding it back to your InfluxDB instance.

You might consider visiting the community site for this kind of assistance.
https://community.influxdata.com

Since this isn't explicitly a documentation issue. I'm going to close this.
