### ISSUE TITLE
Examples for Chaining Methods for BatchNode all seem to declare a StreamNode

### ISSUE THREAD

**Issue by jpellman** [influxdata/docs.influxdata.com#1305]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/nodes/batch_node/

###### What products and version are you using?
Kapacitor 1.3.2 (git: HEAD 2b6a049e5b9dc7d7e8d58a8bbde8d186dc8543e3)

###### Where did you look before opening the issue?
The other issues.  A cursory Github search.

I was just looking at the batch node docs, and all of the examples for the chaining methods declared a stream node, which seemed a bit incongruent.

**Comment by karel-rehor** [comment]
The node documents are being reorganized.  The current documents include a lot of copy paste of chaining methods.  The reorg shortens the documents and provides links between documents instead of repeating the same examples in every document.  This is staged here. 

http://ec2-54-153-106-230.us-west-1.compute.amazonaws.com:1414/kapacitor/v1.3/nodes/batch_node/

Should be fixed in pull request next week.

**Comment by karel-rehor** [comment]
These documents are generated before release, based on comments in the code base.  It might be possible to change the generator to use comments based on context, however this is a low priority task at the moment.
