### ISSUE TITLE
Update InfluxDB install guide for Debian Stretch

### ISSUE THREAD

**Issue by racer01** [influxdata/docs.influxdata.com#1364]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/introduction/installation/#installation
###### What products and version are you using?
Raspbian/Debian Stretch

**Comment by FrankElias** [comment]
Hi Racer01,
just use the following for Debian Stretch

========
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
test $VERSION_ID = "7" && echo "deb https://repos.influxdata.com/debian wheezy stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "8" && echo "deb https://repos.influxdata.com/debian jessie stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "9" && echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
========

Cheers, F

**Comment by timhallinflux** [comment]
closing in favor of #1366

**Comment by tobyweston** [comment]
I can install an older version (1.0.2) just running `sudo apt-get install influxdb` on a clean Stretch install. Any pointers to where that was setup / maintained? I'd like to understand if whatever that mechanism is, if it can be updated to support 1.5.

The reason being install rpms that depend on influx would be much better and I can include the dependency in a control file rather than ask users to install manually.

**Comment by sanderson** [comment]
@tobyweston I'm curious what happens if you run:

```bash
# update your apt-get db
sudo apt-get update

# if a newer version is detected, update to it
sudo apt-get upgrade influxdb
```

**Comment by tobyweston** [comment]
I’ll give it a go to double check but I ran update first so assumed 1.0.2 was all raspbian standard repos know about...

**Comment by tobyweston** [comment]
```bash
$ sudo apt-get upgrade influxdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
influxdb is already the newest version (1.0.2+dfsg1-1).
Calculating upgrade... Done
The following packages will be upgraded:
  bluez-firmware git git-man gnupg gnupg-agent gpgv libgcrypt20 libperl5.24 perl perl-base perl-modules-5.24 pi-bluetooth
12 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.4 MB of archives.
After this operation, 44.0 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

Got to upgrade some other stuff though! 😄

**Comment by timhallinflux** [comment]
@tobyweston -- the official Debian repositories are maintained by the Debian team.  I reached out to that team based on your inquiry to find out why they are offering such an ancient version.  Here is what I got back:

```Everything in the official Debian repositories has to be built from source, for several reasons.

Free software: The best way to ensure that Debian is 100% free software is to build Debian only with source code that we have inspected.

Users privacy: InfluxDB tracks its users by default, something that we chose to disable in Debian.

Security: you build vendors a ton of libraries, we want to make sure that all packages in Debian use the same versions of libraries so that we (or our users) only have to fix them at one place if we find a bug.

Currently, InfluxDB 1.5.3 is in:
 - Debian unstable
 - Debian testing
 - Ubuntu 18.10 (to be released soon)

Now, if you wanted InfluxDB 1.5.3 to be available for Debian stable users, I would simply suggest that they use the package from unstable as this is a Go program and it is pretty much self-contained.
```

We do offer the pre-compiled build for Ubuntu/Debian through our own repository -- which is regularly maintained from the source contained on GitHub.  Latest is here -- if you need the SHA256 -- check the [downloads page](https://portal.influxdata.com/downloads).

```
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.5.3_amd64.deb
sudo dpkg -i influxdb_1.5.3_amd64.deb
```

You can turn off the "phone home" -- within the [configuration file](https://docs.influxdata.com/influxdb/v1.5/administration/config/#reporting-disabled-false), if you wish.  This isn't mandatory to have running.  We appreciate the limited stats this spends back to us as it allows us to gauge adoption and the version being used.

The software we provide through our downloads page and the repo I've described are "free" OSS bits -- and InfluxData is the company standing behind these bits.  If there is a security issue, we will address it.  We also ensure that we do not incorporate any copyleft licenses.  Also, since InfluxDB is a standalone binary -- there shouldn't be any "package conflicts" like those that exist when using Java.  So, some of the "concerns" being made, while understandable from a general open source perspective, are mitigated significantly as it is in our best interests to maintain stable, free, and secure software for the community use/adoption. 

Hope this helps....

**Comment by tobyweston** [comment]
Thanks @timhallinflux that's super helpful.

My main motivator is to ship software (that depends on influxdb) that doesn't require a user to manually install or configure any dependencies. I've chosen to deploy my stuff through APT so can just add a depends item in the control file. 

Sounds like you guys are doing all you can and I (we) appreciate a) the software and b) the efforts you go to for the OSS commitment. I don't think I can ask my users to setup new package sources or use the debian unstable so it looks like I'm stuck with using 1.0.2. That's awesome though, I'm just happy that's available as a non-manual intervention option! 

Thanks again!

I wonder if the maintainers could disable the user tracking (being built from source and all that) for Debian and if that would better suit their sensibilities..?

**Comment by rosenstand** [comment]
That is what they (Debian) do, @tobyweston.

**Comment by tobyweston** [comment]
Looks like Buster and greater are packing 1.6.4 https://packages.debian.org/buster/influxdb :smile:
