### ISSUE TITLE
Line Protocol documentation is missing.

### ISSUE THREAD

**Issue by shakefu** [influxdata/docs.influxdata.com#1452]
I'm trying to implement a python client since the [official client](https://github.com/influxdata/influxdb-python) is several versions behind and no longer works with the latest version. However, without documentation of the line protocol this is difficult at best.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/write_protocols/

###### What products and version are you using?
InfluxDB 1.5

###### Where did you look before opening the issue?
In the docs.

**Comment by phemmer** [comment]
https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/

**Comment by stevebang** [comment]
The confusion is that what @shakefu thought were headings with no content are actually links to the content -- hover over the headings and click on them to reach the content that @phemmer gave a link to. The links not giving visual cues (i.e., better CSS styles) will be addressed in the next few days. Closing since the content is available.

**Comment by shakefu** [comment]
Yeap... I had no idea those were clickable. Probably put something like "Click here to read the section on ..." in front of those sentences. Thanks guys!
