### ISSUE TITLE
Update all redirects to be 301 redirects

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1508]
Common SEO best practice is to use all 401 redirects in order to pass the link juice from the old page to the new page:
https://moz.com/learn/seo/redirection
https://searchengineland.com/301-302-redirect-best-seo-293795

the following pages use 302 redirects but there might be more:

https://docs.influxdata.com/influxdb/
https://docs.influxdata.com/influxdb/latest/introduction/installation/
https://docs.influxdata.com/kapacitor/latest/
https://docs.influxdata.com/influxdb/latest/administration/config/
https://docs.influxdata.com/chronograf/latest/guides/configure-kapacitor-event-handlers/
https://docs.influxdata.com/telegraf/
https://docs.influxdata.com/chronograf/latest/introduction/installation/
https://docs.influxdata.com/kapacitor/
https://docs.influxdata.com/chronograf/latest/introduction/getting-started/
https://docs.influxdata.com/enterprise_influxdb/
https://docs.influxdata.com/chronograf/latest/guides/dashboard-template-variables/
https://docs.influxdata.com/chronograf/latest/troubleshooting/frequently-asked-questions/
https://docs.influxdata.com/telegraf/latest/
https://docs.influxdata.com/enterprise_kapacitor/
https://docs.influxdata.com/chronograf/latest/guides/
https://docs.influxdata.com/influxdb/latest/query_language/authentication_and_authorization/
https://docs.influxdata.com/chronograf/latest/guides/monitor-an-influxenterprise-cluster/
https://docs.influxdata.com/telegraf/latest/introduction/installation/
https://docs.influxdata.com/influxdb/latest/
https://docs.influxdata.com/chronograf/
https://docs.influxdata.com/influxdb/latest/administration/authentication_and_authorization/
https://docs.influxdata.com/chronograf/latest/administration/managing-security/
https://docs.influxdata.com/kapacitor/latest/tick/expr/
https://docs.influxdata.com/influxdb/latest/supported_protocols/opentsdb
https://docs.influxdata.com/influxdb/latest/supported_protocols/graphite
https://docs.influxdata.com/chronograf/latest/administration/managing-chronograf-users/
https://docs.influxdata.com/kapacitor/latest/nodes/alert_node/
https://docs.influxdata.com/chronograf/latest/introduction
https://docs.influxdata.com/influxdb/latest/supported_protocols/prometheus
https://docs.influxdata.com/kapacitor/latest/tick/
https://docs.influxdata.com//kapacitor/latest/guides/event-handler-setup/
https://docs.influxdata.com/influxdb/latest/concepts/glossary/
https://docs.influxdata.com/kapacitor/latest/api/api/
https://docs.influxdata.com/influxdb/latest/query_language/functions/
https://docs.influxdata.com/influxdb/latest/query_language/spec/
https://docs.influxdata.com/influxdb/latest/supported_protocols/udp
https://docs.influxdata.com/influxdb/latest/supported_protocols/collectd

**Comment by sanderson** [comment]
This might get a little tricky. All of these redirects should actually be temporary redirects (302) since the the "latest" version will change in the future. All these redirect to the latest version of each project. By using 301 redirects, when we release new versions, anyone who has visited the site will still be pointed to the previous version by the 301 redirect since it's cached in their browser. These redirect caches are notoriously hard to flush.

I know we (@stevebang and I) have talked about the best way to handle "latest" docs is to duplicate them in an actual `latest` directory, so no redirect would be necessary. I think this would be the better way to go. There's other intricacies like including canonical tags on the actual latest version docs (not in the latest directory).

To do away with the current redirects on the unversioned project landing pages, what we could do is give each of those landing pages with information about the project and links to each of the different versions.

**Comment by russorat** [comment]
@sanderson i agree, the default should be to keep everyone on the page url with `/latest/` in it as long as possible. for all other redirects though, in order to pass the previous page's search ranking to the new page, it should be a 301 redirect using status codes, not javascript.

**Comment by sanderson** [comment]
Just to touch base on this again, all the URLs you list have something to do with `latest` URLs. Those that don't include `latest` are all redirected to a path that uses a `$<project>_latest` variable. Switching these to 301s will cause issues whenever we update latest version.

Because of this, I believe 302 redirects are the appropriate redirect type to use. Everything other than `latest`-related redirects should and do (as far as I've found) use 301s.

**Comment by russorat** [comment]
using 302 redirects means we will lose any SEO value from the page that is redirecting.

right or wrong, every SEO guide recommends using only 301 redirects on websites. https://moz.com/learn/seo/redirection
