### ISSUE TITLE
Recommendations for shard duration values

### ISSUE THREAD

**Issue by stevebang** [influxdata/docs.influxdata.com#1528]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/concepts/schema_and_data_layout/#shard-group-duration-management

From an InfluxDB Enterprise customer: “I have already set all of our databases to 7 days shard duration. None of our databases have greater than 90 days of retention period. You guys might want to add notes for specific use case or update the InfluxDB docs as it recommends to set shard duration to 7 days if RP is > 6 months.

Let's review the recommendations and provide more scenarios and use cases.

**Comment by stevebang** [comment]
@timhallinflux says our default is seven days and that we'd typically tell a customer to set it longer if the RP is > six months.  @e-dard and @dgnorton -- Can you provide any recommendations and useful scenarios?

**Comment by gunnaraasen** [comment]
@e-dard brings up a good point. The impact of the number of shards on performance should be benchmarked and tested, preferably in CI. My thoughts below all draw from my experience with InfluxDB on version 1.4 and earlier.

Shard group duration is a trade-off between flexibility and cost.

A shorter shard group duration provides flexibility by creating more shards. Retention policies can remove old shard data faster since a smaller amount of time needs to pass before a whole shard expires. In a cluster context, small shards can make the balancing of data in a cluster more equal.

A longer shard group duration will reduce the resource costs of having many shards. Each existing shard requires additional memory and CPU to service, e.g. space in the index, internal shard stats collection, etc. There is an impact on baseline resource usage when an InfluxDB instance has thousands of shards.

Overall, many of the reasons we originally recommended shorter shard group durations are no longer applicable, while the reasons to use longer shard group durations remain. We should lean towards recommending a longer shard group duration. I've revised the table in the docs with some "better" values (again, would be great to test these).

| RP Duration     | Shard Group Duration |
|-----------------|----------------------|
| 1 day or less  | 6 hours               |
| 2 to 7 days    | 1 day                |
| 8 to 90 days   | 7 days               |
| 91 days or more | 30 days              |

Maybe a loose rule of thumb could be:

1 <= (RP duration / Shard group duration) <= 12

There are a couple other cases where a non-standard shard group duration makes sense:

1. The retention policy duration is infinite
2. Backfilling years worth of data

In both cases, the shard group duration should be set very high, like 365 days. (Maybe we should consider making an infinite shard group duration.)
