### ISSUE TITLE
Document Technical Analysis Algorithms in InfluxQL

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1553]
https://github.com/influxdata/influxdb/pull/9260
- exponential_moving_average
- double_exponential_moving_average
- triple_exponential_moving_average
- relative_strength_index
- triple_exponential_average
- kaufmans_efficiency_ratio (commonly referred to as just "Efficiency Ratio")
- kaufmans_adaptive_moving_average
- chande_momentum_oscillator

**Comment by phemmer** [comment]
Per request over on #9260

> @phemmer Any chance you could give me a quick rundown of required and optional arguments for each of these functions?

`exponential_moving_average(FIELD, PERIOD[, HOLD_PERIOD[, WARMUP_TYPE]])`  
`double_exponential_moving_average(FIELD, PERIOD[, HOLD_PERIOD[, WARMUP_TYPE]])`  
`triple_moving_average(FIELD, PERIOD[, HOLD_PERIOD[, WARMUP_TYPE]])`  
`triple_exponential_derivative(FIELD, PERIOD[, HOLD_PERIOD[, WARMUP_TYPE]])`  
`relative_strength_index(FIELD, PERIOD[, HOLD_PERIOD[, WARMUP_TYPE]])`  
* `PERIOD` (int, min=1):  
The sample size of the algorithm. This is basically the number of historical samples which have any significant effect on the output of the algorithm. E.G. `2` means the current point and the point before it. The algorithm uses an exponential decay rate to determine the weight of a historical point, generally known as the alpha (α) (NOTE: this means it is possible older points can still have an impact). The `PERIOD` controls that decay rate.
* `HOLD_PERIOD` (int, min=-1, default=`-1`):  
How many samples the algorithm needs before it will start emitting results. The default of `-1` means the value is based on the algorithm, the `PERIOD`, and the `WARMUP_TYPE`, but is a value in which the algorithm can emit meaningful results. (see table at bottom)
* `WARMUP_TYPE` ({`'simple'`,`'exponential'`}, default=`'exponential'`):  
This controls how the algorithm initializes itself for the first `PERIOD` samples, basically the duration for which it has an incomplete sample set.
  * `'simple'`:  
Simple moving average (SMA) of the first `PERIOD` samples. This is the method used by ta-lib.
  * `'exponential'`:  
Exponential moving average (EMA) with scaling alpha (α). This basically uses an EMA with period=1 for the first point, period=2 for the second point, etc, until algorithm has consumed `PERIOD` number of points. As the algorithm immediately starts using an EMA, when this method is used and `HOLD_PERIOD` is unspecified or `-1`, the algorithm will start emitting points after a much smaller sample size than with `'average'`.

&nbsp;

`kaufmans_efficiency_ratio(FIELD, PERIOD[, HOLD_PERIOD])`  
`kaufmans_adaptive_moving_average(FIELD, PERIOD[, HOLD_PERIOD])`
* `HOLD_PERIOD`: Same as above, but the default is `PERIOD`.
Otherwise the parameters are the same as above.

&nbsp;

`chande_momentum_oscillator(FIELD, PERIOD[, HOLD_PERIOD, [WARMUP_TYPE]])`  
* `WARMUP_TYPE` ({`'none'`,`'exponential'`,`'simple'`}, default=`'none'`):  
Basic operation is the same as `WARMUP_TYPE` above, but has an extra option.
  * `'none'`:  
The algorithm does not perform any smoothing at all. This is the method used by ta-lib. When this method is used and `HOLD_PERIOD` is unspecified, `HOLD_PERIOD` defaults to `PERIOD - 1`.
  * `'simple'`,`'exponential'`:  
Same as the definitions for these values from above, with the added note that when used, the algorithm uses smoothing (as opposed to `'none'`).

All other parameters are the same as above.

----

Defaults for `HOLD_PERIOD`:

|                                   | simple                 | exponential | none       |
|-----------------------------------|------------------------|-------------|------------|
| exponential_moving_average        | PERIOD - 1             | PERIOD - 1  |            |
| double_exponential_moving_average | ( PERIOD - 1 ) * 2      | PERIOD - 1  |            |
| triple_exponential_moving_average | ( PERIOD - 1 ) * 3      | PERIOD - 1  |            |
| triple_exponential_derivative     | ( PERIOD - 1 ) * 3 + 1 | PERIOD      |            |
| relative_strength_index           | PERIOD                 | PERIOD      |            |
| chande_momentum_oscillator        | PERIOD                 | PERIOD      | PERIOD - 1 |
