### ISSUE TITLE
Cannot perform a simple query to find a percentage

### ISSUE THREAD

**Issue by nzhammer** [influxdata/docs.influxdata.com#1572]
Hello,

I am attempting to perform a query to find a simple percentage, but have been struggling.

I'm looking for something as simple as this:
`SELECT gain_amount / sum(gain_amount) FROM sells`
But get the error that I cannot mix aggregate and non-aggregate queries. This is confusing to me because the following works:

`SELECT gain_amount / 123 FROM sells`
which seems like the same thing to me, as sum only returns one value, 123.

I've also tried:
`SELECT gain_amount / (SELECT sum(gain_amount) FROM sells ORDER BY DESC LIMIT 1) FROM sells`
which fails as in issue #5684 below

I saw the sub query implementation as I showed below and have tried to get extremely creative with those to no avail. I've tried the following any **many** different spins on it:

`SELECT gain_amount / "sum" FROM (SELECT sum(gain_amount) FROM sells)`
Which returns an empty set, i'm assuming because it doesn't know where my first gain_amount is coming from due to the fact that my sub-query has to be after the FROM keyword.

Any help here? I must be missing something simple.

###### What products and version are you using?
v 1.5.1

###### Where did you look before opening the issue?
I found https://github.com/influxdata/influxdb/issues/5684, which was closed with https://github.com/influxdata/influxdb/issues/4619, but does not seem to resolve the issue at all.

**Comment by timhallinflux** [comment]
Hi @nzhammer... this could be a doc issue. (i.e. why don't we have a better example within the query language documentation examples which shows this kind of thing...)  But, this is probably more like a "usage" question.  How are folks achieving this kind of thing with InfluxQL?  Have you explored https://community.influxdata.com  that is the place where these kinds of questions probably should land.

**Comment by timhallinflux** [comment]
It would be useful to understand how time relates to the query you've structured here and what that implies in terms of the percentage you are attempting to generate. 

The challenge with what you are attempting to do --- is related to the summation and how that relates to the points themselves.  Time marches on -- and if you are gathering and capturing additional data points the sum changes too.  I believe that this kind of query implies that you have a static data set, meaning....for a fixed window of time, you want to evaluate the % that each point contributes to the whole within that fixed time boundary.... is that correct?

**Comment by nzhammer** [comment]
Hi @timhallinflux , I see how it could be somewhat ambiguous. What I am trying to do is to find the percentage at the point in time in which I run the query. A simple but stupid example would be that each time you add an apple to a basket, you want to see what percent of the total weight that the added apple made up. So, when you add the first 70 gram apple it is simply 100% (70/70). Then, you add a second apple that weighs 80 grams, so the query would now report 53.33% (80/150).

I think that a query like this could only be interpreted in that way, but influx's nested queries do not seem to allow you to have an outer FROM clause when using a sub-select.

SELECT apple_weight / (SELECT sum(apple_weight) FROM apple_basket) FROM apple_basket ORDER BY time DESC LIMIT 1;

Sorry if it's a documentation / usage question, but the fact that there was a previous issue around this that was linked to a resolved issue that didn't seem to resolve it had me thinking it was more of a bug.

**Comment by sanderson** [comment]
After looking at the proposed queries, I believe there are actually 2 issues with what you're trying to do:

1. Mixing aggregate data (`sum()`) with non-aggregate data.
2. Aggregate data needs a `GROUP BY` clause.

Aggregate functions don't aggregate all of a field's data points. They aggregate data points that fall within the interval or tag set specified in the `GROUP BY` clause. So using your example of apples in a basket, if there are 30lbs of apples and that is reported 3 times within the specified `GROUP BY time` interval, the result of the `sum()` function will actually be 90. That isn't what you're looking for.

The reason you can't mix aggregate and non-aggregate data is because aggregate data has fewer data points since it's aggregating data. So aggregate and non-aggregate data won't have matching timestamps and therefore cannot be compared to each other at given timestamps.

The solution would be to use either aggregate or non-aggregate functions for **all** referenced data. Using the apple weight example, you'd likely need to create and store a separate `apple_basket.total_weight` field to compare against.

#### Calculate Percentage from Non-aggregate Data
```sql
SELECT (apple_weight/total_weight)*100 AS "apple_pct_weight" FROM apple_basket
```

#### Calculate Percentage from Aggregate Data
```sql
SELECT (mean(apple_weight)/mean(total_weight))*100 AS "mean_apple_pct_weight" FROM apple_basket GROUP BY time(3m)
```

This will compare the mean of `apple_weight`s in 3 minute intervals to the mean of `total_weight`s in the same 3 minute intervals.

**Note:**, you could also use the `cumulative_sum()` function to calculate a running total of `apple_weight`s, but this can be a pretty taxing query. I'd suggest using a [continuous query](https://docs.influxdata.com/influxdb/v1.5/query_language/continuous_queries/) or a [TICKscript](https://docs.influxdata.com/kapacitor/v1.5/tick/introduction/) to continually aggregate and update the `total_weight` field.

In regards to updating the documentation, I think this issue primary stems from a misunderstanding of how aggregate functions work. This could possibly be more clear.

**Comment by sanderson** [comment]
If you were to use the `CUMULATIVE_SUM` function (which is an aggregate function) instead of storing a `total_wieght` field, it would look something like this:

```sql
SELECT (mean("apple_weight")/cumulative_sum(mean("apple_weight"))) AS "apple_pct_weight" FROM "apple_basket" WHERE time >= '2018-06-04T00:00:00Z' AND time <= '2018-06-05T00:00:00Z' GROUP BY time(3m)
```

_Including the limited time range will keep the query from overwhelming your host's resources._

**Comment by sanderson** [comment]
Here's a gist with sample data and and example: https://gist.github.com/sanderson/4a59a213b9d5186d5519b32d2d1a5a88

**Comment by nzhammer** [comment]
Thanks a ton @sanderson for all the help! Just got back to this one.
