### ISSUE TITLE
Influxdb performance issue 

### ISSUE THREAD

**Issue by singhjassi751** [influxdata/docs.influxdata.com#1642]
Hello,
I have issue related to influxdb performance.  version(1.5)
writes  are 3 to 4 thousand per seconds. 
Series cardinality is high.
Machine configuration is 8 cores and 32 gb RAM.
retention policy is of 4 weeks and shard duration is 1 day.

when i refresh the grafana( version 4.6) dasboard it takes more than 2 minutes to load the dashboard.
i want to reduce the dashboard loading time from munutes to couple of seconds.
what changes can be made in influx config file to achieve such level of performance. 
or any other changes which could help me to come out of this problem.
Please help.

**Comment by sanderson** [comment]
Hi @singhjassi751, issues on the `influxdata/docs.influxdata.com` repo should be specific to the InfluxData documentation rather than troubleshooting. I'd suggest posting this to the [Influx Community](https://community.influxdata.com/) to get help from others who may have run into the same issue. If the solution is something that others can benefit from, we'll be happy to include it in the documentation. For now, I'm going to mark this issue as closed.
