### ISSUE TITLE
Need to update kapacitor security documentation for insecure-skip-verify option

### ISSUE THREAD

**Issue by nlevchuk** [influxdata/docs.influxdata.com#1675]
Hi there.

On the page https://docs.influxdata.com/kapacitor/v1.5/administration/security/ in `Kapacitor and InfluxDB HTTPS` section need to specify changes in influxdb.conf

```
[subscriber]
  ....

  # Allows insecure HTTPS connections to subscribers.  This is useful when testing with self-
  # signed certificates.
  insecure-skip-verify = false
```

It's important for self-signed certificate to set this value to `true`. In production environment it must be set to 'false'

If you agree with that i'll make a PR

**Comment by nlevchuk** [comment]
If it does not set this value to `true` for self-signed certificate it leads to `x509: certificate signed by unknown authority` error

**Comment by sanderson** [comment]
@nlevchuk, This must be set to true if using a self-signed certificate, whether it's in production or not. A PR is welcome.

**Comment by nlevchuk** [comment]
@sanderson i think it's not a good idea to set false the option in production using SSL. Anyway i'll update the documentation as i said above

**Comment by sanderson** [comment]
If using any certificate with a fully valid certificate authority, this should be set to `false`. It should _only_ be set to true if using a self-signed certificate. This option skips the certificate verification process that ensures a certificate is signed by a recognized certificate authority.

The reason this is necessary with self-signed certificates is because they are not signed by a recognized certificate authority and will error out during the verification process.

It's not necessarily a bad thing to use a self-signed certificate in a production infrastructure, especially if the internal network is encapsulated behind a firewall. However, attempts to verify the self-signed cert will always fail.

So this setting isn't dependent on the environment (dev vs prod), it's dependent on the type of certificate. If not using a self-signed certificate, you should always allow the verification process to happen for security reasons.
