### ISSUE TITLE
Add link to new swap input plugin readme

### ISSUE THREAD

**Issue by danielnelson** [influxdata/docs.influxdata.com#1702]
We have added a README for the swap input plugin that should be added to the input plugin list.

###### URL for relevant page?

https://docs.influxdata.com/telegraf/v1.7/plugins/inputs/

###### What products and version are you using?

Telegraf 1.7

###### Where did you look before opening the issue?

https://github.com/influxdata/telegraf/issues/4290

**Comment by sdomino** [comment]
It looks like all `system` inputs are grouped under the [System heading](https://docs.influxdata.com/telegraf/v1.7/plugins/inputs#system-system-https-github-com-influxdata-telegraf-tree-release-1-7-plugins-inputs-system).

Would it be preferable to update the System section body to be more descriptive of what "sub" inputs it includes, or bring `swap` and others (cpu, disk, memory, etc.) out?

Although they technically reside under [system](https://github.com/influxdata/telegraf/tree/release-1.7/plugins/inputs/system), It seems more intuitive to find them on this list individually, rather than grouped under a more generic heading.

**Comment by danielnelson** [comment]
I would like to ungroup these plugins, to reduce confusion between system plugins and the system plugin and in the code to have a more unified style.
