### ISSUE TITLE
Chronograf makes references to InfluxDB OSS -- when it should be InfluxDB

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1859]
###### URL for relevant page?
example:
https://docs.influxdata.com/chronograf/v1.6/guides/monitoring-influxenterprise-clusters/#step-4-explore-the-monitoring-data-in-chronograf

The functionality presented isn't necessarily specific to InfluxDB OSS -- it equally applies to InfluxDB Enterprise as well.  We should comb through the Chronograf docs to call out where there are differences specifically between the Enterprise and OSS Data Sources.  But, otherwise, leave the reference "generic."

**Comment by noramullen1** [comment]
In the linked example, I think the doc actually intentionally specified InfluxDB OSS here because it's a tutorial on how to set up InfluxDB OSS to monitor an InfluxDB Enterprise cluster...let me know if I'm misunderstanding though.

I ran a search in the rest of the Chronograf (v1.6) docs and didn't see any other examples that needed changing.

**Comment by stevebang** [comment]
Closing since not an issue.
