### ISSUE TITLE
telegraf system plugin links wrong

### ISSUE THREAD

**Issue by pabigot** [influxdata/docs.influxdata.com#1976]
With the merge of telegraf [issue 4406](https://github.com/influxdata/telegraf/pull/4406#issuecomment-421450823) the links to formerly subordinate plugins are wrong.

E.g. right under https://docs.influxdata.com/chronograf/v1.7/guides/using-precreated-dashboards/#system there's a link to the "Required Telegraf Plugin: CPU input plugin" that produces a 404 because it moved.

**Comment by noramullen1** [comment]
Because all of the headings in the Telegraf docs are links to GitHub, the heading ID is a long string based on the GitHub URL and the resulting anchor link is crazy. For example, the anchor link to the apache plugin is: `https://docs.influxdata.com/telegraf/v1.7/plugins/inputs/#apache-apache-https-github-com-influxdata-telegraf-tree-release-1-7-plugins-inputs-apache`.

In addition to being messy, it has the version number in it. Is there a more elegant way to handle this? @stevebang @sanderson

**Comment by noramullen1** [comment]
@stevebang and I discussed and he's going to remove GitHub links from the headings in the Telegraf docs.

**Comment by sanderson** [comment]
100% support this. We just need to be aware that removing the links is going to break A LOT of anchored links (that I've recently fixed). There will be a substantial cleanup process that needs to happen.

We should still include the Github link along with each plugin description. I'm wondering if we should do a styled "View on Github" button.

**Comment by noramullen1** [comment]
This is fixed. Thanks for letting us know @pabigot!
