### ISSUE TITLE
Provide more how-to information related to logs / log viewer

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#1998]
The majority of information about logs in InfluxDB/Chronograf currently provided in the docs is reference material with very little how-to information.

Requests from the SEs and Engineering team:
- Document the process of setting up Syslog
- Document syslog format

A lot of this is covered in the [Telegraf Syslog plugin readme](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog#readme) and just needs to be formalized in the docs.

**Comment by leodido** [comment]
=> Here there is a complete setup: https://github.com/leodido/logs2metrics-talk

It demos a complete task, with also a kapacitor UDF counting some kind of events from received logs.
That repo contains YAML for Kubernetes, too.
Plus code to develop/debug it locally (I'm referring to the docker compose).

---

Anyway a simpler setup would involve to just use the syslog docker log driver.

In such case there will be ...

**Cons**
Namely no octet framing, thus only UDP transport (since our telegraf syslog input plugin does not allow to disable octet framing for TCP/TLS atm, if I do not remember wrongly)
Fixed syslog facility value.

**And pros**
No rsyslog + mmkubernetes module step (that translates journald logs to RFC5424/RFC5425 syslog messages before they reach telegraf in the complete setup linked above).
