### ISSUE TITLE
Telegraf list of version documentation is out of order

### ISSUE THREAD

**Issue by kensel** [influxdata/docs.influxdata.com#2017]
###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.9/administration/configuration/

The list of versions is out of order causing confusion as to the latest version without scanning through the list.  See attached.

![image](https://user-images.githubusercontent.com/6167437/49187793-e3716880-f325-11e8-8212-9e527e6dd8c2.png)

**Comment by stevebang** [comment]
Fixed in master - changes appear in next published docs

**Comment by digikin** [comment]
I don't want to get an old issue reopened but this happened again. 

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.11/data_formats/input/
###### What products and version are you using?
1.9
###### Where did you look before opening the issue?
Documentation.  
I am not sure if its an issue per-say but it could just be a website error.  On the left side of the document page it shows the v1.10 before v1.11.  This shows the releases in order but it looks like the page displays the order like v1.10/ v1.11/ v1.9.
I was researching differences between v1.9 and v1.10 but became confused because of the placement. 
![Screenshot from 2019-06-22 09-56-18](https://user-images.githubusercontent.com/25944964/59964826-063ab880-94d4-11e9-9a54-7731f55def2f.png)
