### ISSUE TITLE
Remove version number from docs urls

### ISSUE THREAD

**Issue by amok** [influxdata/docs.influxdata.com#207]
It's proposal
Reason:
F.e. docs.influxdata.com/influxdb/**v0.8**/ is in top of google and other SE, but current version is 0.10 - easy to overlook and confusing

**Comment by gunnaraasen** [comment]
There is a warning at the top of all doc pages for old versions and the version number in the URL allow links to old documentation to persist so they're discoverable for users who are still on v0.8.

We're open to suggestions to improve the warning, but the URLs will not be changed.

**Comment by brettdh** [comment]
I'd suggest that you're overlooking the real problem here because the proposed solution isn't palatable. The real problem here - that google indexes old versions and presents them first, almost every time I search - doesn't happen for just about any other project I can think of. For example, consider Python docs hosted on readthedocs.org - say, pexpect. Searching for '[pexpect spawn][pexpect-rtfd]' shows, as its number two hit, a link to readthedocs with "stable" as the version. Whenever a new version is released, the doc URLs and google results don't change, so search remains useful. You can still easily get to old versions' documentation using the version selector at the bottom, and indeed those versions' URLs haven't changed.

Further, the current state of the docs optimizes for people who are on old versions - which is probably not the common case, especially for a project like TICK that is in a state of rapid iteration and improvement. It would be better to optimize for the common case here (searching for the latest version's docs).

The warning would be more useful if it linked to the same page or content that I was viewing in the old version. As it is, I might as well just search for "influxdb" every time, because I'm not going to find the specific thing I'm looking for from Google (or anywhere else, as the docs are not searchable).

Based on this, I propose that this issue be renamed (e.g. "Docs are not searchable, internally or externally") and reopened so that this problem can be addressed, in some way that maintains the ability to search for old docs as well, as you mentioned.

[pexpect-rtfd]: https://www.google.com/webhp?ion=1&espv=2&ie=UTF-8#q=pexpect+spawn

**Comment by amok** [comment]
++
@brettdh that's what I aimed to say:) tnx

**Comment by beckettsean** [comment]
@brettdh @amok we are adding search to the docs very soon, and are working to get google to index the new pages more frequently.

**Comment by dandv** [comment]
> We're open to suggestions to improve the warning, but the URLs will not be changed.

https://docs.influxdata.com/influxdb/latest/introduction/getting_started/ already works.

The warning should contain a link to the `latest` version of the page.

Also, how about adding

    <link rel="canonical" href="...link to the latest version">

in the `<head>` of old documentation pages? That should promote the current docs first in SERPs.
