### ISSUE TITLE
Undefined term "measurement" in InfluxDB Line Protocol tutorial

### ISSUE THREAD

**Issue by bslade** [influxdata/docs.influxdata.com#2085]
The [line_protocol_tutorial](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/) defines the first "component" (field) of a "Line Protocol" line as a "measurement", but then gives an example where the first component is a category of measurements

Specifically, in the example in the [line_protocol_tutorial](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/), the first "component" (field) of the "Line Protocol" is "Weather", and the "field sets" are "temperature" and "bug_concentration".

But calling "Weather" a measurement is inaccurate.   It's really a category of measurements and "temperature" and "bug_concentration" are the actual measurements.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/

###### What products and version are you using?
influxdb/v1.7

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/

**Comment by sanderson** [comment]
Thanks for the feedback @bslade. The term "measurement" used here refers to a measurement within InfluxDB's data structure. A link to this definition is provided under the ["Measurement" section of the doc](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/#measurement) you've referenced in this issue. (Here's the direct link to the definition: [measurement](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#measurement)).

Within the InfluxDB data structure, a measurement is a logical group of fields. While you are correct in saying that the fields contained in the example "measurement" represent values _measured_ from somewhere, when stored in InfluxDB, they are stored as [fields](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#field) inside of a [measurement](https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#measurement).

 The name of the measurement is arbitrary, but should represent a logical grouping of the fields/data stored in it. I have updated the provided example slightly since I don't think `bug_concentration` would be stored as weather data. I changed it to `humidity`.

Thank you for the feedback. If you have any questions, please feel free to ping me.
