### ISSUE TITLE
For sandbox installation, step to add user to docker group is missing

### ISSUE THREAD

**Issue by ajgreyling** [influxdata/docs.influxdata.com#2229]
I was following the steps on the URL below. I installed docker using packages. 
Error received when calling `$ ./sandbox up`

```
Using latest, stable releases
Spinning up Docker Images...
If this is your first time starting sandbox this might take a minute...
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
```
Fix: Add user to docker group

`$ sudo usermod -aG docker ${USER}`

###### URL for relevant page?
https://docs.influxdata.com/platform/installation/sandbox-install

###### What products and version are you using?
InfluxData Sandbox -  Ubuntu Xenial 64amd 

###### Where did you look before opening the issue?
StackOverflow, Google. Found the answer on a medium post : https://medium.com/@ibrahimgunduz34/if-you-faced-an-issue-like-couldnt-connect-to-docker-daemon-at-http-docker-localunixsocket-is-27b35f17d09d

**Comment by sanderson** [comment]
Thanks @ajgreyling. This page is meant to be OS-agnostic and focus primarily on the running the sandbox. The `sudo usermod ...` step is unique to Ubuntu and is part of the Docker installation process. It's covered in the Docker Ubuntu installation instructions [here](install-using-the-convenience-script) (using Docker as a non-root user). Since it is OS-specific and part of the Docker installation process, it is out of scope for this article.
