### ISSUE TITLE
Update HTTP API documentation re: bind params

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2708]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/tools/api/#bind-parameters

###### What products and version are you using?
Documentation describes that bind-parameters is only for the `where` clause.  This changes with 1.8. See details here: https://github.com/influxdata/influxql/pull/34

**Comment by jsternberg** [comment]
To clarify, bind parameters have always worked everywhere in the query. In 1.8, bind parameters will now support more parts of the AST they can bind too. The above change makes it so you can bind identifiers, regexes, and durations.

The existing bind parameters have always worked everywhere in the query. It has been possible since the first version of bind parameters to do `LIMIT $n` because `n` is an integer literal.

**Comment by pierwill** [comment]
Closed via https://github.com/influxdata/docs.influxdata.com/pull/2710.
