### ISSUE TITLE
More content on sql.from() page

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs.influxdata.com#2714]
###### URL for relevant page?

https://docs.influxdata.com/flux/v0.50/stdlib/sql/from/

###### What products and version are you using?

InfluxDB OSS, Cloud 2

###### Where did you look before opening the issue?

https://docs.influxdata.com/flux/v0.50/stdlib/sql/from/

My requests are as follows:

#1: List more databases and code samples

I'm pretty sure that sql.from() supports MariaDB, AWS RDS (for MySQL, Postgres, maybe Maria), and Google BigTable (or BigQuery?). But that's the point: I shouldn't have to guess. This page should list all the databases that sql.from() supports.

Also, we should have code samples for each supported database. Even if the code samples are identical (for instance, MySQL vs. MariaDB), it will help a developer if they can simply grab the right code snippet and drop it into their Flux code.

#2: Code snippets using secret store

Since /flux/v0.50/stdlib/sql/from/ shows usernames and passwords in cleartext, the page should have an example of how to both store a username and password in the secret store, as well as how to later retrieve and use that username and password in the dataSourceName variable in sql.from. 

Right now, there are bits and pieces of how to do this in the two below pages, but nothing that walks me through the process, end-to-end, for setting/getting database secrets.

https://v2.docs.influxdata.com/v2.0/security/secrets/use-vault/

https://www.influxdata.com/blog/using-secret-stores-to-secure-flux-access/

**Comment by sanderson** [comment]
@alsargent The page currently lists all the databases that our engineers are confident in supporting. Each database driver is different and we've found that when building the integrations, they each need some adjustment to correctly import data into Flux. MariaDB and Percona may already work since they're forks of MySQL and should be drop-in replacements, but as far as I know, they haven't been tested. Google BigTable has it's own experimental package: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/bigtable/.

Before listing other databases, we need to make sure they're sufficiently vetted and the appropriate Go drivers have been tested. This is something that will likely be up to the Flux team.

I'm going to create a separate issue for showing how to use secrets with database connections. There is an example [here](https://v2.docs.influxdata.com/v2.0/security/secrets/#use-secrets-in-a-query), but we could better illustrate how to use them in the SQL docs.
