### ISSUE TITLE
Colors missing for Telegraf, Chronograf, and Kapacitor docs

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#291]
The colors for InfluxDB still show up:

![image](https://cloud.githubusercontent.com/assets/8750814/13579231/26119d04-e451-11e5-9712-8d67a5577029.png)

But, Telegraf, Chronograf, and Kapacitor are missing their colors:

![image](https://cloud.githubusercontent.com/assets/8750814/13579247/4215127e-e451-11e5-8334-8738a5415617.png)

Checked on Chrome and Safari.

**Comment by rkuchan** [comment]
@kostasb - any ideas on why this might be happening?

**Comment by kostasb** [comment]
@rkuchan Docs master branch on staging looks good: http://docs.staging.influxdata.com:31000 so it shouldn't be a code issue. I've tried republishing the Docs live but it didn't fix it. It most probably is an issue with our Content Delivery Network, I'll investigate further.

**Comment by kostasb** [comment]
@rkuchan @gunnaraasen 

Fixed. Please check and confirm if everything looks good - might need to refresh your browser a couple of times to clean up its cache.

Details: Looks like our content delivery network (CloudFront) suddenly started respecting the metadata Content Type on S3 bucket files. CSS files that were marked as text/plain in the Content Type field of the S3 bucket were not executed, thus coloring and other attributes were not applied on website objects. I have upgraded our publish process to explicitly mark CSS files with the necessary text/css metadata so that CloudFront will run them.

**Comment by rkuchan** [comment]
@kostasb Everything looks good on my end! Thank you for looking into and fixing that.
