### ISSUE TITLE
0.10.1 cluster failed when it's binding address configured to listen on all interfaces.

### ISSUE THREAD

**Issue by jeyan123** [influxdata/docs.influxdata.com#295]
###### Where did you look before opening the issue? https://docs.influxdata.com/influxdb/v0.10/clustering/cluster_setup/

I have configured the binding addresses to listen on all the interfaces, 
* Single node (hybride) works 
* Cluster failed, it always set it to localhost.

[meta]
bind-address = ":8088"
http-bind-address = ":8091"

[http]
bind-address = ":8086"

Thanks,
JR

**Comment by beckettsean** [comment]
@jeyan123 please [open an issue](https://github.com/influxdata/influxdb/issues/new) on the InfluxDB repo, since this is not a bug with the documentation.

When you open the bug, please give more details. Many people have set up a cluster using those directions, so if it's not working for you the answer is in the details.
