### ISSUE TITLE
Tag keys and field keys update

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#482]
https://github.com/influxdata/influxdb/issues/6519

Search for issue: https://github.com/influxdata/influxdb/issues/4630

**Comment by beckettsean** [comment]
@jsternberg what was the resolution to the duplicate tag and field name combo?

I've seen reference to the `field::foo` syntax but we don't have anything but short PR comments to go on. Can you spend a little time to explain the new syntax, when it's valid, when it's not, etc.?

**Comment by jsternberg** [comment]
@beckettsean the resolution was that any field name is now of the format `<name>::<type>`. The `::<type>` is optional and, if omitted, the query engine will determine a default. The default resolution order is:

* If a field exists, use the field's type
* If a tag exists, use the `tag` type
* Else, it will return null values

The field types are determined _before_ any iterators are created so that the type is consistent across shards.

The types you can use are `float`, `integer`, `string`, `boolean`, `field`, and `tag`. If you specify the type for any of these, it will only select what you chose. So if you chose `integer` but you have some shards with floats and some with integers, it will convert all of them to integers. If you select `string` and one of the shards has floats, the floats will just be ignored. If you select `field`, any tags that may exist with that name with be ignored, but the data type chosen will follow normal precedence rules (`float` > `integer` > `string` > `boolean`). If you select `tag`, fields will be ignored and a tag will be selected. If no tag exists, it will just be a blank string that always gets returned.

For wildcards, only `*::field` and `*::tag` are allowed and you can't specifically cast a certain field to a specific type using wildcards (like you can't select all strings at the moment, although that might be a good idea for a feature request). The wildcards will expand to include all fields or all tags for a measurement.

Does this help?

**Comment by beckettsean** [comment]
Thanks, @jsternberg that's great info.

Looks like `*::field` is not valid inside functions, correct?

**Comment by jsternberg** [comment]
Yes, none of the wildcards are supported inside of functions yet.

**Comment by beckettsean** [comment]
@jsternberg My testing seems to be at odds with the described behavior:

```
> insert if value=42i 1
> insert if value=42.42 1000000000000000
> insert if value=42i 100000000000000000
> insert if value=42.42 1000000000000000000
> select * from "if"
name: if
--------
time				value
1970-01-01T00:00:00.000000001Z	42
1970-01-12T13:46:40Z		42.42
1973-03-03T09:46:40Z		42
2001-09-09T01:46:40Z		42.42
```

Half the `value` values are floats, the other half are integers.

Selecting for integers does return the float values cast into integers.

```
> select value::integer from "if"
name: if
--------
time				value
1970-01-01T00:00:00.000000001Z	42
1970-01-12T13:46:40Z		42
1973-03-03T09:46:40Z		42
2001-09-09T01:46:40Z		42

> 
```

However, selecting only the floats still returns the integers. Are they cast as floats now?

```
> select value::float from "if"
name: if
--------
time				value
1970-01-01T00:00:00.000000001Z	42
1970-01-12T13:46:40Z		42.42
1973-03-03T09:46:40Z		42
2001-09-09T01:46:40Z		42.42

> 
```

It seems that "If you specify the type for any of these, it will only select what you chose. " isn't quite accurate. The numeric types will be cast into the requested type, not excluded from the results.

**Comment by jsternberg** [comment]
The reason why you see that behavior is because of Javascript/JSON limitations. JSON can't identify the difference between a float and an integer (and, in fact, it treats everything as floats).

And yea, the wording I used could be better. It will perform the cast operation to move the type to another type. If no cast operation is available to go from the shard type to the requested type, the value is dropped.

**Comment by beckettsean** [comment]
Thanks, further testing shows that one downside is `SELECT * ` no longer returns all points:


Using 30m shards so I can easily have multiple types:
```
> insert types value=T 1464973585000000000
> insert types value="string" 1464970585000000000
> insert types value=42i 1464960585000000000
> insert types value=42.0042 1464950585000000000
> select * from types
name: types
-----------
time			value
2016-06-03T10:43:05Z	42.0042
2016-06-03T13:29:45Z	42
```

The boolean and string points are excluded from the `SELECT *`, which is as designed, but probably not quite expected behavior. @rkuchan we need to be very up-front about this in the docs. I can still get all four points in one query, but not with a single wildcard:  

```
> select value::string from types
name: types
-----------
time			value
2016-06-03T16:16:25Z	string

> select value::boolean from types
name: types
-----------
time			value
2016-06-03T17:06:25Z	true

> select value, value::string, value::boolean from types
name: types
-----------
time			value	value_1	value_2
2016-06-03T10:43:05Z	42.0042		
2016-06-03T13:29:45Z	42		
2016-06-03T16:16:25Z		string	
2016-06-03T17:06:25Z			true

```

That said, having mixed field types is a data smell, so it's not a failing that the database doesn't behave intuitively when field types are mixed. The most common issue by far is float/int mixups, and those are now easier to handle.

**Comment by jsternberg** [comment]
I don't think `SELECT *` was able to return all data points if there were conflicting types previously. One positive of this change is that `SELECT *` will now return both the field and tag if those are named the same. Previously, the field masked the tag.

**Comment by beckettsean** [comment]
Yeah, on 0.13 it returns the timestamps for each point but empty field values except for the numeric ones:

```
> insert types value=T 123456789
> insert types value="string" 1234567890000000
> insert types value=42 1234567890000000000
> select * from types
name: types
-----------
time			value
123456789		
1234567890000000	
1234567890000000000	42

> 
```

Thanks for the more predictable and flexible syntax, Jonathan!

**Comment by adampl** [comment]
Hi. For me, as a user, the idea of a `tag` type is ugly because it's not really a type, and selecting either a field or a tag by the same name using the typecast sounds like a very dirty hack. I know I'm late in this discussion, but for me the idea of prepending tag name with a `@` was much better.

Also it would be nice if selecting all fields or all tags, or both (grouped separately as fields and tags) were possible - and it would be consistent with the way the data is written.

**Comment by beckettsean** [comment]
@adampl please comment on the InfluxDB repo to discuss the syntax. The docs don't determine the syntax, they just record it.

https://github.com/influxdata/influxdb/issues/6519 and https://github.com/influxdata/influxdb/pull/6410 are the relevant issues/PRs.
