### ISSUE TITLE
Doc update request: use of telegraf.d

### ISSUE THREAD

**Issue by bluebob** [influxdata/docs.influxdata.com#486]
Running Telegraf 0.13.1 and noticed that the startup uses `/etc/telegraf/telegraf.conf` and `/etc/telegraf/telegraf.d/*.conf`. Can we get some further details on how to use these, e.g.:
1. When to use `telegraf.conf` and when to use separate `*.conf` files? I've used a file in `telegraf.d`, but Telegraf's startup bitched that `telegraf.conf` didn't exist, (I created a dummy file in /etc/telegraf)
2. Precedence order: if `telegraph.conf` exists but so do `telegraf.d` files, is the resulting config the union of both, and if a setting is referred to multiple times then is it the last reference in `telegraf.d` that takes effect?
3. If I define an input and output stream in a `telegraf.d` conf file is that a single distinct dataflow? As an example if I have three configuration files in telegraf.d

```
A.conf: input kafka, output elasticsearch
B.conf: input snmp, output influxdb
C.conf: input docker, output file
```

Am I going to get kafka, snmp and docker all going to elasticsearch and influx and file (multiplex) or am I going to get kafka going to elasticsearch only, snmp to influxdb only and docker to file only?

Point #3 is important for me at the moment, because I'm looking at Telegraf as a interface between multiple Kafka topics and a collection of InfluxDB and Elasticsearch databases. If T'graf can deal with those separate data flows then that'd (obviously!) be a cleaner solution than having to run a T'graf instance for each data flow.

Yes, I know I could probably figure this out by looking at the code, but I'm only just past "hello world" in Go-lang at the moment [grin]

**Comment by beckettsean** [comment]
@kostasb @sparrc @gunnaraasen can you help?

**Comment by sparrc** [comment]
you can basically just think of it as all the *.conf files in telegraf.d getting summed up into a single file (so yes, it's a union). There is no precedence because Telegraf allows for creating multiple instances of the same plugin type, so duplicates would get run more than once. This shouldn't really harm anything but would be wasteful of resources.

There is no concept of separating dataflows by config file. You can run multiple dataflows within a single config file by utilizing measurement filters to determine which measurements go to which output (see https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering)

Number (1) is probably a bug, if there is a valid file in telegraf.d we should be able to start Telegraf without specifying a singular .conf file.

**Comment by artburkart** [comment]
If I wanted to get this issue closed out, what would I have to do?

**Comment by timhallinflux** [comment]
@danielnelson -- can you comment further on what should happen her wrt to docs for this style of config?

**Comment by danielnelson** [comment]
1. This is arguably a bug, please feel free to open an issue on the Telegraf github.  Generally people put the agent section in the main telegraf.conf and the plugin configs in the telegraf.d directory.
2. There is no ordering to the sections in a Telegraf config.
3. The dataflow in a Telegraf instance can be controlled via the measurement filtering options, which file a definition is in does not matter.

**Comment by danielnelson** [comment]
I did make a minor modification to the upcoming 1.4 documentation https://github.com/influxdata/docs.influxdata.com/commit/0638b52fdc153aee232f7755a91ca0a2b44e4a8e.
