### ISSUE TITLE
CREATE USER syntax

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#531]
https://github.com/influxdata/influxdb/pull/6890#issuecomment-232776783

**Comment by beckettsean** [comment]
@jsternberg Can you clarify what query examples should be in the docs? 

`CREATE USER foo WITH PASSWORD 'secret'` works, and there is no `ALTER USER` statement. Are you saying that `CREATE USER foo WITH PASSWORD 'new secret'` should update an existing user's password?

**Comment by jsternberg** [comment]
`CREATE USER` doesn't update a password, but there's a common need inside of configuration management software to check if a user/password exists so that the software can then perform any modifications if necessary. A note inside of `CREATE USER` that calling that with the same username and password will return a noop would help anybody who was trying to use it that way. I don't think that's currently documented at the moment.

**Comment by beckettsean** [comment]
Gotcha, thanks! Does it return 204?

**Comment by jsternberg** [comment]
No, same response as if it had created it. It's a bit unfortunate since I think that people implementing this will still have to call `SHOW USERS` anyway to determine if the user exists.
