### ISSUE TITLE
Confusing warning on Kapacitor derivative function

### ISSUE THREAD

**Issue by timraymond** [influxdata/docs.influxdata.com#596]
I'm not really sure what this means: "Deriviative is not a MapReduce function and as a result is not part of the normal influxql functions." It doesn't make sense to me because it implies that there _are_ MapReduce functions... given that there is only one instance of Kapacitor running, there would be nothing to "map" them to. Is this a warning? Does this say that derivative works differently than the one in InfluxQL?

After Googling for other references to this, I found this doc page: https://docs.influxdata.com/kapacitor/v0.10/nodes/map_node/. Was this removed in a subsequent making "MapReduce functions" vestigial terminology?

###### URL for relevant page?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/nodes/derivative_node.md

###### What products and version are you using?

Kapacitor v0.13

###### Where did you look before opening the issue?

Exclusively at the doc page for derivative. Also briefly looked on the doc page search for other references in the docs to "MapReduce" functions, but this seems to be the only instance for v0.13. I found other references by doing a `site:docs.influxdata.com mapreduce` query on Google.

**Comment by rossmcdonald** [comment]
Regarding:

> Is this a warning? Does this say that derivative works differently than the one in InfluxQL?

I would consider this to be more of a "notice" than a warning. Originally, if you wanted to call an InfluxQL function, you had to use a `.mapReduce()` node. This notice is just saying, "don't use .mapReduce(), just call .derivative()", if that makes sense.

> Was this removed in a subsequent making "MapReduce functions" vestigial terminology?

They were renamed to just "InfluxQL nodes", since the MapReduce terminology and syntax was confusing: https://docs.influxdata.com/kapacitor/v0.13/nodes/influx_q_l_node/

I think that the sentence should be removed entirely, though, as it's really no longer relevant. @nathanielc, what do you think?

**Comment by nathanielc** [comment]
@timraymond @rossmcdonald  You are correct that the `MapReduce` terminology has been removed. 

But it is still true that Kapacitor has its own implementation of the `derivative` function instead of using the implementation from InfluxDB. That is the point of the notice, but like you say may not be all that important.

**Comment by rossmcdonald** [comment]
What if instead of:

> Derivative is not a MapReduce function and as a result is not part of the normal influxql functions.

It just said:

> Kapacitor has its own implementation of the derivative function, and, as a result, is not part of the normal InfluxQL functions.

This would remove the MapReduce term, and make it clear that Kapacitor has a separate implementation of derivative. Thoughts?

**Comment by nathanielc** [comment]
@rossmcdonald  LGTM
