### ISSUE TITLE
404 on Telegraf 'Getting Started'

### ISSUE THREAD

**Issue by azilber** [influxdata/docs.influxdata.com#709]
###### URL for relevant page?
'Getting Started' link on this page:
https://www.influxdata.com/time-series-platform/telegraf/

404 here:
 https://docs.influxdata.com/telegraf/v1.0/introduction/getting-started-telegraf/

**Comment by beckettsean** [comment]
@toddboom looks like the issue is on the www side.

On https://www.influxdata.com/time-series-platform/telegraf/, the Getting Started button should link to 
https://docs.influxdata.com/telegraf/v1.0/introduction/getting_started/
not
https://docs.influxdata.com/telegraf/v1.0/introduction/getting_started-telegraf/

**Comment by gunnaraasen** [comment]
I just updated the site. The link should work now.

**Comment by beckettsean** [comment]
Confirmed fixed.
