### ISSUE TITLE
[InfluxDB] Subqueries are here!

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#951]
Create a new section in the Data Exploration doc.

### Description

A subquery is a query that is nested in the `FROM` clause of another query. The syntax allows users to apply a query as a condition in a super query. Subqueries offer the same functionality as nested functions and SQL `HAVING` clauses.

> **Note:** This feature is a technical preview and considered under development. Do not use this feature in your production systems. If you have questions regarding this feature, contact Support by logging a case on our Support Portal at **URL**.

### Syntax
```
SELECT_clause FROM ( SELECT_statement) WHERE_clause [...]
```

### Description of Syntax
* Super query, sub query terminology
* In the `FROM` clause, requires parentheses
* You can do more than one subquery

### Examples
* Super simple one
* Nested function
* HAVING clause
* You can separately set the lower time boundary and upper time boundary in the super and sub query
* This is cool: `SELECT MAX("a"),"min_b" FROM (SELECT MIN("b") AS "min_b" FROM "bulldogs")`
* So is this: `SELECT sum(derivative) FROM (SELECT derivative(mean(value)) FROM cpu GROUP BY *)`

### Common Issues/Gotchas
* `GROUP BY`s must appear in both the super query and the subquery
* `GROUP BY tag` is covered in both clauses (my notes suck, need to test this out)
* If including a `GROUP BY time()` clause, the `WHERE time` clause can appear in either the super or sub query
* If `ORDER BY time` appears in both the sub and super query, then the one in the super query takes precedence
* If there are conflicting time intervals between the super- and sub-queries, the most recent timestamps win out

(Maybe do an issue all about conflict resolution)

### Also requires updates to:
* [x] The FAQ about nested functions
* [x] The FAQ about INTO queries (I think!)
* [x] The CQ doc's use case section
Will need to note the tech preview status of this feature in those docs as well.

**Comment by rkuchan** [comment]
I ended up not documenting the `HAVING` clause functionality because of this issue: https://github.com/influxdata/influxdb/issues/7841. I also created a `Known Issues` section instead of a `Common Issues` section because I believe subqueries are still under development.

**Comment by Macfresno** [comment]
As you explain this it seems that subqueries works on any "FROM" clausule, but I'm trying to use it in a SHOW TAG VALUES query and it don't work:

`SHOW TAG VALUES FROM (SELECT top("in_bytes","id", 10) FROM (SELECT derivative("in_bytes",1s) as in_bytes FROM "net" WHERE time > now() - 30m GROUP BY "id" LIMIT 1) WHERE time > now() - 30m  LIMIT 10) WITH KEY = "id" `

I know that the second parent query is not needed, because with this query:

`SELECT top("in_bytes","id", 10) FROM (SELECT derivative("in_bytes",1s) as in_bytes FROM "net" WHERE time > now() - 30m GROUP BY "id" LIMIT 1) WHERE time > now() - 30m  LIMIT 10`

I already have all information I need, but I need the output of SHOW TAG VALUES in grafana's templating.

Am I doing something wrong or I will never be able to do a subquery with a SHOW TAG VALUES statement?
