### ISSUE TITLE
[Enterprise] Align backup-restore with new code implementation

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#987]
Influxd-ctl restore now expects a directory instead of a manifest as stated in http://docs.influxdata.com/enterprise/v1.2/guides/backup-and-restore/#restore

In case you want to restore a single manifest file: `influxd-ctl restore -full MANIFEST` (it should have been created during a full backup)

The fix for `close source #969` is to error out with a warning that a file was provided when a directory containing the backups was expected.

+restore in the docs doesn't show the `-full` option

```
root@meta1:~# influxd-ctl restore -h
Usage: influxd-ctl restore [options] ( <manifest> | <directory> )
    Restores data backed up from a cluster

Arguments:
    <manifest> specifies the file to use.

Options:
  -db string
    	Database to restore, if more than one in backup
  -full
    	Perform a restore from a full backup
  -list
    	List the contents of the backup
  -newdb string
    	Change database name when restoring, requires '-db'
  -newrf int
    	New replication factor used during restore, capped to cluster size
  -newrp string
    	Change retention policy name when restoring, requires '-rp'
  -rp string
    	Retention policy to restore, if more than one in backup
  -shard uint
    	Shard ID to restore


```

@rkuchan @rossmcdonald @gunnaraasen we'll update the docs as soon as possible

**Comment by kostasb** [comment]
restoring manifests requires the -full option at the moment

`influxd-ctl restore -full -db xyz -newdb abc ./20161223T180119Z.manifest`

**Comment by joelegasse** [comment]
To add some more context: `-full` is meant for point-in-time backups (everything prior to 1.2). Without `-full` specified, the default behavior expects a directory where the incremental backups will be stored. The `-full` flag is not meant to be arbitrarily turned on/off, and the two uses should probably not be mixed without knowing the implications. This is especially true for `restore`.

When using `-full`:
- Each `backup` creates a point-in-time backup
- Each `restore` takes a specific manifest, and restores all the data (or a subset if `-db` is used), from that backup

When not using `-full` (default, incremental):
- Each `backup` adds shards that have changed since the last backup, and records the latest metadata
- All backups should be in the same directory
- `restore` should be given the backup directory, and will restore the latest data (point-in-time restore from incremental backups are currently not supported)
- `-db` can still be used to restore a single database (and `-newdb` can be used to rename it)

Recommendations:
- Do not mix `-full` backups and incremental backups (use a different directory).
- Do not attempt `restore -full` with a manifest created from an incremental backup (and expect all the data to be there)

**Comment by rkuchan** [comment]
Fixed in https://github.com/influxdata/docs.influxdata.com/pull/988. Will require some editing once 1.2.2 comes out. That information is in this issue: https://github.com/influxdata/docs.influxdata.com/issues/1017
